nail_master_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("nail_service.urls", namespace="nail_service")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nail_service/urls.py
from django.urls import path

from . import views
from .views import (
    index, MasterListView, MasterDetailView, MasterCreateView, MasterDeleteView, ServicesListView, CustomerListView,
    CustomerDetailView, CustomerCreateView, CustomerDeleteView, ServicesCreateView, ServicesUpdateView,
    ServicesDeleteView, MasterUpdateView, PriceListCreateView, PriceListUpdateView, PriceListDeleteView,
    CustomerUpdateView,
    )


urlpatterns = [
    path("", index, name="index"),  
    path("master/", MasterListView.as_view(), name="master-list"),
    path(
        "master/<int:pk>/", MasterDetailView.as_view(), name="master-detail"
    ),
    path("master/", MasterListView.as_view(), name="master-list"),
    path("master/create/", MasterCreateView.as_view(), name="master-create"),
    path('master/<int:pk>/update/', MasterUpdateView.as_view(), name='master-update'),
    path(
        "master/<int:pk>/delete/",
        MasterDeleteView.as_view(),
        name="master-delete",
    ),
    path("services/", ServicesListView.as_view(), name="services-list"),
    path(
        "services/create/",
        ServicesCreateView.as_view(),
        name="services-create",
    ),
    path(
        "services/<int:pk>/update/",
        ServicesUpdateView.as_view(),
        name="services-update",
    ),
    path(
        "services/<int:pk>/delete/",
        ServicesDeleteView.as_view(),
        name="services-delete",
    ),
    path("customer/", CustomerListView.as_view(), name="customer-list"),
    path(
        "customer/<int:pk>/", CustomerDetailView.as_view(), name="customer-detail"
    ),
    path('customer/<int:pk>/update/', CustomerUpdateView.as_view(), name='customer-update'),
    path("customer/create/", CustomerCreateView.as_view(), name="customer-create"),
    path(
        "customer/<int:pk>/delete/",
        CustomerDeleteView.as_view(),
        name="customer-delete",
    ),
    path("all_events/", views.all_events, name="all_events"),
    path("add_event/", views.add_event, name="add_event"),
    path("update/", views.update, name="update"),
    path("remove/", views.remove, name="remove"),
    path("master/<int:pk>/create_price_list/", PriceListCreateView.as_view(), name="price-list-create"),
    path("master/<int:pk>/update_price_list/", PriceListUpdateView.as_view(), name="price-list-update"),
    path("master/<int:pk>/delete_price_list/", PriceListDeleteView.as_view(), name="price-list-delete"),
    path('subscribe/<int:pk>/', views.subscribe_to_master, name='subscribe'),
    path('unsubscribe/<int:pk>/', views.unsubscribe_from_master, name='unsubscribe'),
]

app_name = "nail_service"

templates/includes/header.html
<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top pt-4 header-container" style="background-color: transparent !important;">
  <div class="container-fluid d-flex align-items-center">
    <a class="navbar-brand ps-5" href="{% url 'nail_service:index' %}">
      <img src="/static/img/logo.jpg" alt="Logo" width="100" height="70" class="d-inline-block align-text-center logo">
      Nail Master Service
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto justify-content-center">
        <li class="nav-item pe-5">
          <a class="nav-link active" aria-current="page" href="{% url 'nail_service:index' %}">Home</a>
        </li>
        <li class="nav-item pe-5">
          <a class="nav-link" href="{% url 'nail_service:master-list' %}">All masters</a>
        </li>
        <li class="nav-item pe-5">
          <a class="nav-link" href="{% url 'nail_service:customer-list' %}">All customers</a>
        </li>
        <li class="nav-item pe-5">
          <a class="nav-link" href="{% url 'nail_service:services-list' %}">All services</a>
        </li>
      </ul>
      <div class="dropdown ms-auto">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          User: {{ user.get_username }}
        </button>
        <ul class="dropdown-menu">
          {% if user.is_authenticated %}
            {% if user.role == 'MASTER' %}
            <li><a class="dropdown-item" href="{% url 'nail_service:master-detail' pk=user.id %}">User details</a></li>
            
            <li><a class="dropdown-item" href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
            {% elif user.role == 'CUSTOMER' %}
            <li><a class="dropdown-item" href="{% url 'nail_service:customer-detail' pk=user.id %}">User details</a></li>
            <li><a class="dropdown-item" href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
            {% else %}
            <li><a class="dropdown-item" href="{% url 'nail_service:index' %}">User details</a></li>
            <li><a class="dropdown-item" href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
            {% endif %}
          {% else %}
          <li><a class="dropdown-item" href="{% url 'login'%}?next={{request.path}}">Login</a></li>
          {% endif %}
          
          
        </ul>
      </div>
    </div>
  </div>
</nav>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}