nail_master_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("nail_service.urls", namespace="nail_service")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nail_service/urls.py
from django.urls import path

from . import views
from .views import (
    index, MasterListView, MasterDetailView, MasterCreateView, MasterDeleteView, ServicesListView, CustomerListView,
    CustomerDetailView, CustomerCreateView, CustomerDeleteView, ServicesCreateView, ServicesUpdateView,
    ServicesDeleteView, MasterUpdateView, PriceListCreateView, PriceListUpdateView, PriceListDeleteView,
    CustomerUpdateView,
    )


urlpatterns = [
    path("", index, name="index"),  
    path("master/", MasterListView.as_view(), name="master-list"),
    path(
        "master/<int:pk>/", MasterDetailView.as_view(), name="master-detail"
    ),
    path("master/", MasterListView.as_view(), name="master-list"),
    path("master/create/", MasterCreateView.as_view(), name="master-create"),
    path('master/<int:pk>/update/', MasterUpdateView.as_view(), name='master-update'),
    path(
        "master/<int:pk>/delete/",
        MasterDeleteView.as_view(),
        name="master-delete",
    ),
    path("services/", ServicesListView.as_view(), name="services-list"),
    path(
        "services/create/",
        ServicesCreateView.as_view(),
        name="services-create",
    ),
    path(
        "services/<int:pk>/update/",
        ServicesUpdateView.as_view(),
        name="services-update",
    ),
    path(
        "services/<int:pk>/delete/",
        ServicesDeleteView.as_view(),
        name="services-delete",
    ),
    path("customer/", CustomerListView.as_view(), name="customer-list"),
    path(
        "customer/<int:pk>/", CustomerDetailView.as_view(), name="customer-detail"
    ),
    path('customer/<int:pk>/update/', CustomerUpdateView.as_view(), name='customer-update'),
    path("customer/create/", CustomerCreateView.as_view(), name="customer-create"),
    path(
        "customer/<int:pk>/delete/",
        CustomerDeleteView.as_view(),
        name="customer-delete",
    ),
    path("all_events/", views.all_events, name="all_events"),
    path("add_event/", views.add_event, name="add_event"),
    path("update/", views.update, name="update"),
    path("remove/", views.remove, name="remove"),
    path("master/<int:pk>/create_price_list/", PriceListCreateView.as_view(), name="price-list-create"),
    path("master/<int:pk>/update_price_list/", PriceListUpdateView.as_view(), name="price-list-update"),
    path("master/<int:pk>/delete_price_list/", PriceListDeleteView.as_view(), name="price-list-delete"),
    path('subscribe/<int:pk>/', views.subscribe_to_master, name='subscribe'),
    path('unsubscribe/<int:pk>/', views.unsubscribe_from_master, name='unsubscribe'),
]

app_name = "nail_service"

nail_service/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from django.urls import reverse


class Services(models.Model):
    name = models.CharField(max_length=255, unique=True)
    price = models.DecimalField(max_digits=1000, decimal_places=2)
    time_service = models.TimeField(auto_now=False, auto_now_add=False)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} {self.price} {self.time_service}"


class User(AbstractUser):

    class Role(models.TextChoices):
        ADMIN = "ADMIN", 'Admin'
        CUSTOMER = "CUSTOMER", 'Customer'
        MASTER = "MASTER", 'Master'

    base_role = Role.ADMIN

    role = models.CharField(max_length=50, choices=Role.choices)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.role = self.base_role
        return super().save(*args, **kwargs)


class Customer(User):
    base_role = User.Role.CUSTOMER

    services = models.ManyToManyField(Services, related_name="customer_services")
    masters = models.ManyToManyField('Master', related_name="customer_customers", verbose_name="Customer masters")

    user = models.OneToOneField(User, on_delete=models.CASCADE, parent_link=True)

    class Meta:
        ordering = ["id"]

    def get_absolute_url(self):
        return reverse("nail_service:customer-detail", kwargs={"pk": self.pk})


class Master(User):
    base_role = User.Role.MASTER

    user = models.OneToOneField(User, on_delete=models.CASCADE, parent_link=True)

    services = models.ManyToManyField(Services, related_name="master_services", through='PriceList')
    customers = models.ManyToManyField('Customer', related_name="master_customers", verbose_name="Master customers")

    class Meta:
        ordering = ["id"]
        permissions = [
            ("view_own_master", "Can view own master"),
            ("change_own_master", "Can change own master"),
            ("change_service_price", "Can change service price"),
        ]

    def get_absolute_url(self):
        return reverse("nail_service:master-detail", kwargs={"pk": self.pk})


class Events(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    master = models.ForeignKey(Master, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class PriceList(models.Model):
    master = models.ForeignKey(Master, on_delete=models.CASCADE)
    service = models.ForeignKey(Services, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=1000, decimal_places=2)
    time_service = models.TimeField(default=None, null=True, blank=True, auto_now=False, auto_now_add=False)

    class Meta:
        ordering = ["service"]

    def __str__(self):
        return f"Master: {self.master}, Service: {self.service}, Price: {self.price}, Time_for_service: {self.time_service}"

nail_service/views.py
from datetime import datetime
from typing import Any, Optional, Dict, List

from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.db.models import QuerySet
from django.http import JsonResponse, HttpResponseForbidden, HttpResponseRedirect, HttpResponse, HttpRequest
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, get_object_or_404
from .forms import (MasterCreationForm, MasterSearchForm, ServicesSearchForm,
                    CustomerSearchForm, CustomerCreationForm, ServicesCreateForm,
                    PriceListForm)
from .models import User, Services, Master, Customer, Events, PriceList


@login_required
def index(request: HttpRequest) -> HttpResponse:
    """View function for the home page of the site."""
    num_masters: int = Master.objects.count()
    num_customers: int = Customer.objects.count()
    num_visits: int = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_masters": num_masters,
        "num_customers": num_customers,
        "num_visits": num_visits + 1,
    }

    return render(request, "nail_service/index.html", context=context)


@login_required
def user_details(request) -> HttpResponseRedirect:
    """View function to handle user details based on their role."""
    user = request.user
    if request.user.role == User.Role.MASTER:
        # User has the 'Master' role
        return HttpResponseRedirect(f'/master/{user.pk}')
    elif request.user.role == User.Role.CUSTOMER:
        # User has the 'Customer' role
        return HttpResponseRedirect(f'/customer/{user.pk}')
    else:
        # User has no specific role assigned
        return render(request, 'nail_service/index.html')


def admin_required(view_func) -> callable:
    """
    Decorator function to check if the user has the 'Admin' role.
    Raises PermissionDenied if the user does not have the required role.
    """
    def wrapper(request, *args, **kwargs) -> callable:
        if request.user.role != User.Role.ADMIN:
            raise PermissionDenied("You do not have permission to perform this action.")
        return view_func(request, *args, **kwargs)
    return wrapper


def master_required(view_func) -> callable:
    """
    Decorator function to check if the user has the 'Master' role.
    Raises PermissionDenied if the user does not have the required role.
    """
    def wrapper(request, *args, **kwargs) -> callable:
        if request.user.role != User.Role.MASTER:
            raise PermissionDenied("You do not have permission to perform this action.")
        return view_func(request, *args, **kwargs)
    return wrapper


def customer_required(view_func) -> callable:
    """
    Decorator function to check if the user has the 'Customer' role.
    Raises PermissionDenied if the user does not have the required role.
    """
    def wrapper(request, *args, **kwargs) -> callable:
        if request.user.role != User.Role.CUSTOMER:
            raise PermissionDenied("You do not have permission to perform this action.")
        return view_func(request, *args, **kwargs)
    return wrapper


class MasterListView(LoginRequiredMixin, generic.ListView):
    """
    View class to display a list of masters.
    Requires user authentication.
    """
    model = Master
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(MasterListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = MasterSearchForm(initial={"username": username})
        return context

    def get_queryset(self):
        queryset = Master.objects.filter(role="MASTER")
        form = MasterSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(username__icontains=form.cleaned_data["username"])

        return queryset.order_by("id")


class MasterUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    permission_required = "nail_service.change_own_master"
    model = Master
    form_class = MasterCreationForm
    success_url = reverse_lazy("nail_service:master-list")
    template_name = "nail_service/master_update_form.html"

    def form_valid(self, form) -> HttpResponse:
        """
        Performs additional operations when the form is valid.
        Saves the master object, updates the price list, and returns the result of the parent's form_valid method.
        """
        services = form.cleaned_data.get('services', [])
        self.object = form.save(commit=False)
        self.object.save()
        PriceList.objects.filter(master=self.object).delete()
        for service in services:
            price = form.cleaned_data.get('price_' + str(service.id))
            PriceList.objects.create(master=self.object, service=service, price=price)
        return super().form_valid(form)

    def test_func(self) -> bool:
        """
        Checks if the user has permission to update the master details.
        Returns True if the user matches the master's user, False otherwise.
        """
        return self.request.user == self.get_object().user

    def handle_no_permission(self) -> HttpResponse:
        """
        Handles the case when the user does not have permission to update the master details.
        Returns an HTTP Forbidden response with a rendered template for 403 error.
        """
        return HttpResponseForbidden(render_to_string('nail_service/403.html', {
            'error_message': self.get_permission_denied_message()
        }))


class MasterDetailView(LoginRequiredMixin, generic.DetailView):
    model = Master
    queryset = Master.objects.filter(role=User.Role.MASTER)
    template_name = 'nail_service/master_detail.html'

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        """
        Adds event data to the context for displaying in the master detail page.
        """
        context = super().get_context_data(**kwargs)
        master = self.object

        events = Events.objects.filter(master_id=master.id).select_related("master")
        event_data = []
        for event in events:
            event_data.append({
                'title': event.title,
                'id': event.id,
                'start': event.start_date.strftime("%Y-%m-%d %H:%M:%S"),
                'end': event.end_date.strftime("%Y-%m-%d %H:%M:%S"),
            })

        context['event_data'] = event_data
        return context


class MasterCreateView(generic.CreateView):
    model = Master
    form_class = MasterCreationForm
    success_url = reverse_lazy("nail_service:master-list")
    template_name = "nail_service/master_form.html"

    def form_valid(self, form) -> HttpResponse:
        """
        Performs additional operations when the form is valid.
        Saves the master object and updates the price list.
        Returns the result of the parent's form_valid method.
        """
        services = form.cleaned_data.get('services', [])
        self.object = form.save(commit=False)
        self.object.save()
        for service in services:
            price = form.cleaned_data.get('price_' + str(service.id))
            PriceList.objects.create(master=self.object, service=service, price=price)
        return super().form_valid(form)


class MasterDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    permission_required = "nail_service.change_own_master"
    model = Master
    success_url = reverse_lazy("nail_service:master-list")

    def test_func(self) -> bool:
        """
        Checks if the user has permission to delete the master.
        Returns True if the user matches the master's user, False otherwise.
        """
        return self.request.user == self.get_object().user

    def handle_no_permission(self) -> HttpResponse:
        """
        Handles the case when the user does not have permission to delete the master.
        Returns an HTTP Forbidden response with a rendered template for 403 error.
        """
        return HttpResponseForbidden(render_to_string('nail_service/403.html', {
            'error_message': self.get_permission_denied_message()
        }))


class CustomerListView(LoginRequiredMixin, generic.ListView):
    model = Customer
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs) -> dict[str, Any]:
        """
        Adds search form to the context for displaying in the customer list page.
        """
        context = super().get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = CustomerSearchForm(initial={
            "username": username
        })

        return context

    def get_queryset(self) -> Any:
        """
        Returns the queryset of customers based on the search form's input.
        If the form is valid, filters the queryset based on the username.
        Otherwise, returns the queryset ordered by id.
        """
        queryset = Customer.objects.filter(role="CUSTOMER")
        form = CustomerSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )

        return queryset.order_by("id")


class CustomerUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):

templates/nail_service/customer_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ customer.username }}
    {% if user == customer.user %}
    <a href="{% url 'nail_service:customer-update' pk=customer.id %}" class="btn btn-primary link-to-page">
      Update Customer
    </a>
    <a href="{% url 'nail_service:customer-delete' pk=customer.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>
    {% endif %}

  </h1>

  <p><strong>First name:</strong> {{ customer.first_name }}</p>
  <p><strong>Last name:</strong> {{ customer.last_name }}</p>
  <p><strong>Is staff:</strong> {{ customer.is_staff }}</p>


{% endblock %}

templates/nail_service/customer_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create customer</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/nail_service/customer_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

<h1>All customers</h1>


<form action="" method="get" class="form-inline search-form">
  {{ search_form|crispy }}
  <input class="btn btn-secondary" type="submit" value="🔍">
</form>

    

    {% if customer_list %}
    <table>
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
      </tr>
    {% for customer in customer_list %}
      <tr>
        <td>{{ customer.id }}</td>
        <td><a href="{{ customer.get_absolute_url }}">{{ customer.username }} {% if user == customer %} (Me){% endif %}</a></td>
        <td>{{ customer.first_name }}</td>
        <td>{{ customer.last_name }}</td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no customers in the service.</p>
    {% endif %}
{% endblock %}

templates/nail_service/event_list.html
<script>
    $(document).ready(function () {
        var calendar = $('#calendar').fullCalendar({
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay'
            },
            events: {{ event_data| safe }},
        selectable: true,
        selectHelper: true,
        editable: true,
        eventLimit: true,
        select: function (start, end, allDay) {
            var title = prompt("Enter Event Title");
            if (title) {
                var start = $.fullCalendar.formatDate(start, "Y-MM-DD HH:mm:ss");
                var end = $.fullCalendar.formatDate(end, "Y-MM-DD HH:mm:ss");
                $.ajax({
                    type: "GET",
                    url: '/add_event',
                    data: { 'title': title, 'start': start, 'end': end },
                    dataType: "json",
                    success: function (data) {
                        var eventData = {
                            title: title,
                            start: start,
                            end: end,
                            id: data.id
                        };
                        calendar.fullCalendar('renderEvent', eventData);
                        alert("Added Successfully");
                        calendar.fullCalendar(location.replace(location.href));
                    },

                    error: function (data) {
                        alert('There is a problem!!!');
                    }
                });
            }
        },
        eventResize: function (event) {
            var start = $.fullCalendar.formatDate(event.start, "Y-MM-DD HH:mm:ss");
            var end = $.fullCalendar.formatDate(event.end, "Y-MM-DD HH:mm:ss");
            var title = event.title;
            var id = event.id;
            $.ajax({
                type: "GET",
                url: '/update',
                data: { 'title': title, 'start': start, 'end': end, 'id': id },
                dataType: "json",
                success: function (data) {
                    calendar.fullCalendar('refetchEvents');
                    alert('Event Update');
                },

                error: function (data) {
                    alert('There is a problem!!!');
                }
            });
        },

        eventDrop: function (event) {
            var start = $.fullCalendar.formatDate(event.start, "Y-MM-DD HH:mm:ss");
            var end = $.fullCalendar.formatDate(event.end, "Y-MM-DD HH:mm:ss");
            var title = event.title;
            var id = event.id;
            $.ajax({
                type: "GET",
                url: '/update',
                data: { 'title': title, 'start': start, 'end': end, 'id': id },
                dataType: "json",
                success: function (data) {

                    alert('Event Update');
                },
                error: function (data) {
                    alert('There is a problem!!!');
                }
            });
        },

        eventClick: function (event) {
            if (confirm("Are you sure you want to remove it?")) {
                var id = event.id;
                $.ajax({
                    type: "GET",
                    url: '/remove',
                    data: { 'id': id },
                    dataType: "json",
                    success: function (data) {
                        calendar.fullCalendar('removeEvents', id);
                        alert('Event Removed');
                    },

                    error: function (data) {
                        alert('There is a problem!!!');
                    }
                });
            }
        }
        });
    });
</script>

templates/nail_service/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Nail Master Service Home</h1>
    <p>Welcome to Nail Master service!</p>
    <h2>Dynamic content</h2>
    <p>The nail service has the following record counts:</p>
    <ul>
        <li><strong>Masters:</strong> {{ num_masters }}</li>
        <li><strong>Customers:</strong> {{ num_customers }}</li>
    </ul>

    <div class="col-md-12">
        <div id="calendar"></div>
    </div>


    <p>You have visited this page
        {{ num_visits }} time{{ num_visits|pluralize }}.
    </p>

{% endblock %}

templates/nail_service/master_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete master?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/nail_service/master_detail.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<h1>
  Username: {{ master.username }}
  {% if user == master.user %}
  <a href="{% url 'nail_service:master-update' pk=master.id %}" class="btn btn-primary link-to-page">
    Update Master
  </a>
  <a href="{% url 'nail_service:master-delete' pk=master.id %}" class="btn btn-danger link-to-page">
    Delete
  </a>
  {% endif %}
  

</h1>

<p><strong>First name:</strong> {{ master.first_name }}</p>
<p><strong>Last name:</strong> {{ master.last_name }}</p>
<p><strong>Is staff:</strong> {{ master.is_staff }}</p>

<h2>Price List</h2>
{% if user == master.user %}
<a href="{% url 'nail_service:price-list-create' pk=master.id %}" class="btn btn-primary link-to-page">
  Update Price List
</a>
{% endif %}

{% if master.pricelist_set.all%}
<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Time_service
      <br>
      (HH:MM)
    </th>
    {% if user == master.user %}
    <th>Update</th>
    <th>Delete</th>
    {% endif %}
  </tr>

  {% for item in master.pricelist_set.all %}

  <tr>
    <td>
      {{ item.service.name }}
    </td>
    <td>
      UAH {{ item.price }}
    </td>
    <td>
      {{ item.time_service|time:"H:i" }}
    </td>
    {% if user == master.user %}
    <td>
      <a href="{% url 'nail_service:price-list-update' pk=item.id %}">
        Update
      </a>
    </td>
    <td>
      <a style="color: red" href="{% url 'nail_service:price-list-delete' pk=item.id %}">
        Delete
      </a>
    </td>
    {% endif %}
  </tr>
  {% empty %}
  <p>No services in the price list.</p>
  {% endfor %}
</table>
{% endif %}
<br>
<h2>Customers</h2>

{% if user.role == "CUSTOMER" %}
<a href="{% url 'nail_service:subscribe' pk=master.id %}" class="btn btn-primary">
  Subscribe to this master
</a>
<a href="{% url 'nail_service:unsubscribe' pk=master.id %}" class="btn btn-danger">
  Unsubscribe from this master
</a>
{% endif %}


<hr>
<ul>
  {% for customer in master.customers.all %}
  <li>{{ customer.username }} ({{ customer.first_name }} {{ customer.last_name }})</li>
  {% endfor %}
  <br>
  <hr>


<div id="calendar"></div>

{% block scripts %}
{% include "nail_service/event_list.html" %}
{% endblock %}
{% endblock %}

templates/nail_service/master_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<h1>All masters</h1>

<form action="" method="get" class="form-inline search-form">
  {{ search_form|crispy }}
  <input class="btn btn-secondary" type="submit" value="🔍">
</form>


    {% if master_list %}
    <table>
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
      </tr>
    {% for master in master_list %}
      <tr>
        <td>{{ master.id }}</td>
        <td><a href="{{ master.get_absolute_url }}">{{ master.username }} {% if user == master %} (Me){% endif %}</a></td>
        <td>{{ master.first_name }}</td>
        <td>{{ master.last_name }}</td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no master in the service.</p>
    {% endif %}
{% endblock %}

templates/nail_service/master_update_form.html
{% extends "base.html" %}
{% load custom_filters %}

{% block content %}
  <h1>Update Master</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}



    <button type="submit">Update</button>
  </form>
{% endblock %}

templates/nail_service/pricelist_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete service?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/nail_service/service_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete service?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/nail_service/services_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete service?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/nail_service/services_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} service</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/nail_service/services_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Services List
    {% if user.role != "CUSTOMER" %}

    <a href="{% url 'nail_service:services-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
    {% endif %}


  </h1>

  <div class="row">
    <div class="col-sm-6">
      <form action="" method="get" class="form-inline search-form">
        <div class="form-group">
          {{ search_form|crispy }}
        </div>
        <button class="btn btn-secondary" type="submit">🔍</button>
      </form>
    </div>
  </div>

  
  {% if services_list %}
    <table>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Price</th>
        <th>Time_service</th>
        {% if user.role == "ADMIN" %}

        <th>Update</th>
        <th>Delete</th>
        {% endif %}


      </tr>

      {% for service in services_list %}
        <tr>
          <td>
              {{ service.id }}
          </td>
          <td>
              {{ service.name }}
          </td>
          <td>
              {{ service.price }}
          </td>
          <td>
              {{ service.time_service|time:"H:i" }}
          </td>
          {% if user.role == "ADMIN" %}
          <td>
              <a href="{% url 'nail_service:services-update' pk=service.id %}">
                Update
              </a>
          </td>
          <td>
              <a style="color: red"
                href="{% url 'nail_service:services-delete' pk=service.id %}">
                Delete
              </a>
          </td>
          {% endif %}

        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no services in the service.</p>
  {% endif %}
</div>
{% endblock %}